name: m1meg-gh-polygen
# from template plasmabio-template-python
# with elements from https://github.com/pierrepo/plasma-env-cleblond-score-polygen.git
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
  - genomedk
  - defaults
  - bioconda
  - conda-forge
dependencies:
  # Jupyter dependencies
  - jupyterhub>=1.5,<2
  - jupyterlab>=3.2,<4
  - jupyter-resource-usage
  - jupyterlab-topbar
  - jupyterlab-topbar-text
  - jupyterlab-system-monitor
  - nodejs
  # Python environment
  - python>=3.8
  - pip
  - ipywidgets>=7.6,<8
  - numpy==1.26.4
  - pandas==2.3.1
  - scipy==1.13.1
  - matplotlib
  - seaborn==0.13.2
  - biopython==1.85
  # Jupyter archive
  # https://github.com/jupyterlab-contrib/jupyter-archive
  - jupyter-archive
  - pip:
    - -r requirements.txt
    # Print module version
    - watermark
